import{S as q,i as u,a as v}from"./assets/vendor-D52M-Kao.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const M=document.querySelector("#search-form"),E=document.querySelector('input[name="searchQuery"]'),m=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),O=document.querySelector(".end-message"),$="51262986-c338856f457aa770ab0affaea",P="https://pixabay.com/api/";let c=1,l="",f=0;const g=new q(".gallery a");function h(){p.style.display="block"}function b(){p.style.display="none"}function H(){m.innerHTML=""}function a(t){y.style.display=t?"block":"none"}function d(t){O.style.display=t?"block":"none"}function w(t){return t.map(({webformatURL:r,largeImageURL:n,tags:s,likes:e,views:o,comments:i,downloads:S})=>`
    <a href="${n}" class="photo-card">
      <img src="${r}" alt="${s}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${e}</p>
        <p><b>Views:</b> ${o}</p>
        <p><b>Comments:</b> ${i}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </a>
  `).join("")}async function L(t,r=1,n=40){const s={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n},{data:e}=await v.get(P,{params:s});return e}M.addEventListener("submit",async t=>{if(t.preventDefault(),l=E.value.trim(),!!l){c=1,H(),h(),a(!1),d(!1);try{const{hits:r,totalHits:n}=await L(l,c);if(f=n,r.length===0){u.warning({title:"Oops!",message:"No images found. Try a different keyword."});return}m.innerHTML=w(r),g.refresh(),r.length<40||r.length>=f?(a(!1),d(!0)):a(!0)}catch{u.error({title:"Error",message:"Something went wrong while fetching images."})}finally{b()}}});y.addEventListener("click",async()=>{c++,h(),a(!1),d(!1);try{const{hits:t}=await L(l,c);m.insertAdjacentHTML("beforeend",w(t)),g.refresh(),I(),c*40>=f?(a(!1),d(!0)):a(!0)}catch{u.error({title:"Error",message:"Failed to load more images."})}finally{b()}});function I(){const t=document.querySelector(".photo-card");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
